In [ ]:
#First install Tensorflow
#pip install tensorflow

In [1]:
import tensorflow as tf

In [4]:
tf.__version__

'1.9.0'

In [2]:
first = tf.constant("Hello") # First Node
second = tf.constant(" Tensor") # Second Node


In [3]:
fullword = first + second  # Bridge to connect both node using this third Node
# There are two steps in Tensorflow: 1. first create all node in graph 2. Execute the graph.

In [4]:
fullword

<tf.Tensor 'add:0' shape=() dtype=string>

In [ ]:
# It did not show content of fullword, to get the word we have to do create session

In [5]:
with tf.Session() as sess:
    result = sess.run(fullword)
    tf.summary.FileWriter('tensorboard/hello_world_n.logs',sess.graph)
# To see Tensorboard, open new Dos windows and types this command:
# d:\InstalledSoftware\Anaconda3\envs\tensorflow\Scripts>tensorboard --logdir=E:/Binod/Deep_Learning/TensorFlow_Code/tensorboard

In [6]:
result

b'Hello Tensor'

In [ ]:
#The b prefix is to indicate byte strings rather than unicode strings. The default depends on your python version: 
# python2 str is bytes, but python3 str is unicode

In [7]:
result.decode() # decode method will return the string from bytes.

'Hello Tensor'

## Graph

In [9]:
a = tf.constant(5)
b = tf.constant(7)
c = tf.constant(10)

In [10]:
d = tf.multiply(a,b)
e = tf.add(b,c)
f = tf.subtract(d,e)

In [11]:
with tf.Session() as sess:
    out = sess.run(f)
    tf.summary.FileWriter('tensorboard/graph_test.logs',sess.graph)

In [18]:
out

18

## Fetches

In [12]:
with tf.Session() as sess:
    fetches = [a,b,c,d,e,f]
    outs = sess.run(fetches)
print(outs)

[5, 7, 10, 35, 17, 18]


## Data types

In [38]:
a = tf.constant(57)
a.dtype

tf.int32

In [39]:
b = tf.constant(57.0)
b.dtype

tf.float32

In [13]:
c = tf.constant(57.0, dtype=tf.float64)
c.dtype

tf.float64

## Tensor Arrays and Shapes

In [16]:
c = tf.constant([1,2,3]) # Single Array 1 D
c
sess = tf.Session()
out = sess.run(c)
out

array([1, 2, 3])

In [55]:
d = tf.constant([[1,2,3],[4,5,6]]) # 2 D array

In [57]:
d

<tf.Tensor 'Const_24:0' shape=(2, 3) dtype=int32>

In [61]:
with tf.Session() as sess:
    out = sess.run(d)
out

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
import numpy as np # We can also create numpy array and assign to Tensorflow.

In [18]:
e = np.array([[1,2,3],[4,5,6]])
f = tf.constant(e)
with tf.Session() as sess:
    out2 = sess.run(f)
out2

array([[1, 2, 3],
       [4, 5, 6]])

## Sequence

In [19]:
# Generate 20 different number between 2 to 10.
d = tf.linspace(start=2.0, stop=10.0, num=20)
with tf.Session() as sess:
    out = sess.run(d)
out

array([  2.        ,   2.42105269,   2.84210539,   3.26315784,
         3.68421054,   4.10526323,   4.52631569,   4.94736862,
         5.36842108,   5.78947353,   6.21052647,   6.63157892,
         7.05263138,   7.47368431,   7.89473677,   8.31579018,
         8.73684216,   9.15789413,   9.57894707,  10.        ], dtype=float32)

In [21]:
# Create 4*5 array and filled with 100 all number.
f = tf.fill((4,5),99)
with tf.Session() as sess:
    out = sess.run(f)
out

array([[99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99]])

## Variables 

In [22]:
a = tf.Variable(10)
b = tf.Variable(20)
c = a + b
c

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [23]:
sess = tf.Session()
add = sess.run(c)
print(add)

FailedPreconditionError: Attempting to use uninitialized value Variable
	 [[Node: Variable/read = Identity[T=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Variable)]]

Caused by op 'Variable/read', defined at:
  File "d:\InstalledSoftware\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\InstalledSoftware\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\InstalledSoftware\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "d:\InstalledSoftware\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "d:\InstalledSoftware\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "d:\InstalledSoftware\Anaconda3\lib\site-packages\zmq\eventloop\ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "d:\InstalledSoftware\Anaconda3\lib\site-packages\tornado\ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "d:\InstalledSoftware\Anaconda3\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "d:\InstalledSoftware\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "d:\InstalledSoftware\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "d:\InstalledSoftware\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "d:\InstalledSoftware\Anaconda3\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "d:\InstalledSoftware\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "d:\InstalledSoftware\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "d:\InstalledSoftware\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "d:\InstalledSoftware\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "d:\InstalledSoftware\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "d:\InstalledSoftware\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2698, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "d:\InstalledSoftware\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2802, in run_ast_nodes
    if self.run_code(code, result):
  File "d:\InstalledSoftware\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-22-4f25240fb228>", line 1, in <module>
    a = tf.Variable(10)
  File "d:\InstalledSoftware\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 259, in __init__
    constraint=constraint)
  File "d:\InstalledSoftware\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 422, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "d:\InstalledSoftware\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 79, in identity
    return gen_array_ops.identity(input, name=name)
  File "d:\InstalledSoftware\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 3887, in identity
    "Identity", input=input, name=name)
  File "d:\InstalledSoftware\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "d:\InstalledSoftware\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3414, in create_op
    op_def=op_def)
  File "d:\InstalledSoftware\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value Variable
	 [[Node: Variable/read = Identity[T=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Variable)]]


In [24]:
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
add = sess.run(c)
print(add)

30


In [ ]:
with tf.Session() as sess:
    sess.run(a.initializer)
    sess.run(b.initializer)
    out = sess.run(c)
out

In [25]:
y = tf.Variable(tf.random_normal((300,200),0,1), name='y')
print(y)

<tf.Variable 'y:0' shape=(300, 200) dtype=float32_ref>


In [26]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    out = sess.run(y)
out

array([[ 1.62784505,  1.09939492,  0.82085854, ...,  0.62821424,
         1.25645101, -0.64841551],
       [ 0.41949207, -0.48732179,  0.22782563, ..., -2.03338552,
        -2.16853833, -0.51379311],
       [-0.8181144 ,  0.50701368, -0.47518212, ...,  0.9047156 ,
         0.521972  ,  1.20042312],
       ..., 
       [-0.34760422,  1.38967872, -0.60716313, ..., -0.50573039,
        -0.59710735, -0.75615495],
       [ 1.07692504,  0.30064604, -0.29702219, ...,  1.96884084,
        -1.71774173,  1.49666262],
       [-1.38288391, -1.07457447, -0.63763899, ...,  0.08129503,
        -1.21505511, -0.07165644]], dtype=float32)

In [66]:
# Generating any random number.
init_vals = tf.random_normal((1,5),0,1)
init_vals

<tf.Tensor 'random_normal:0' shape=(1, 5) dtype=float32>

In [67]:
# To use variable, you need global variable initializer
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    out = sess.run(init_vals)
out

array([[ 1.85379148,  0.70858908, -0.63345087,  1.38987648, -2.66568446]], dtype=float32)

## Placeholders

In [27]:
ph = tf.placeholder(tf.int16) # Kind of variable. We will pass value during run time.
d = tf.multiply(ph,2)
with tf.Session() as sess:
    out = sess.run(d,feed_dict={ph:5})
    print(out)
    out = sess.run(d,feed_dict={ph:50})
    print(out)
    print(sess.run(d,feed_dict={ph:500}))

10
100
1000
