In [1]:
# pip install tensorflow==2.0.0
import tensorflow as tf

In [2]:
tf.version

<module 'tensorflow_core._api.v2.version' from '/Users/binod/Documents/software/anaconda/anaconda3/lib/python3.7/site-packages/tensorflow_core/_api/v2/version/__init__.py'>

In [3]:
print(tf.version)

<module 'tensorflow_core._api.v2.version' from '/Users/binod/Documents/software/anaconda/anaconda3/lib/python3.7/site-packages/tensorflow_core/_api/v2/version/__init__.py'>


In [5]:
first = tf.constant("Hello")
second = tf.constant("Tensorflow")
result = first + second

In [6]:
result

<tf.Tensor: shape=(), dtype=string, numpy=b'HelloTensorflow'>

In [7]:
tf.print(result)

HelloTensorflow


In [9]:
# Before TensorFlow 2.0 Version. Please watch my youtube video on TensorFlow 1.9 Version
# https://www.youtube.com/watch?v=vO6YOaCLjgw

#with tf.Session() as sess:
#    result = sess.run(fullword)
#print(result)

## Variable

In [11]:
a = tf.Variable(10)
b = tf.Variable(20)
c = a + b
tf.print(c)

30


## Graph

In [12]:
a = tf.constant(5)
b = tf.constant(7)
c = tf.constant(10)

In [13]:
d = tf.multiply(a,b)
e = tf.add(b,c)
f = tf.subtract(d,e)

In [14]:
tf.print(f)

18


## Fetch to show all intermediate value

In [15]:
fetches = [a,b,c,d,e,f]
tf.print(fetches)

[5, 7, 10, 35, 17, 18]


## Tensor Arrays and Shapes

In [16]:
c = tf.constant([1,2,3]) # Single Array 1 D
tf.print(c)

[1 2 3]


In [26]:
d = tf.constant([[1,2,3],[4,5,6]]) # 2 D array
tf.print(d)

[[1 2 3]
 [4 5 6]]


In [27]:
tf.shape(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

## Sequence

In [29]:
# Generate 20 different number between 2 to 10.
d = tf.linspace(start=2.0, stop=10.0, num=20)
tf.print(d, sep='\r')

[2 2.42105269 2.84210539 ... 9.15789413 9.57894707 10]


In [30]:
tf.shape(d)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([20], dtype=int32)>